Capstone one: Africa Tech Report
jssol/africa-tech-report pull request #2
Opened 2022-02-01 21:01 UTC by jssol

## Capstone one: Africa Tech Report

### Interactions:

- [x] Mobile menu:
  - [x] When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
  - [x] User clicks or taps `X` button, the navigation menu disappears
- [x] Links:
  - [x] The home page should have a link in the menu to the about page.
  - [ ] The logo in the header links to the home page.

### Technical Requirements:

- [x] Personalize the content of the website
- [x] Follow the design guidelines as close as possible
- [x] Should build at least 2 pages:
  - [x] Home page
  - [x] About page
  - [ ] Make them responsive for PCs
- [x] Dynamic page:
  - [x] The section "Featured speakers" should be created dynamically in JavaScript.
  - [x] Store the information about the 'Featured speakers' in an JS array.

### Useful links:
- [Live Url](https://jssol.github.io/africa-tech-report/)
- [Requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/capstone/html_capstone.md)

2022-02-02 10:34 UTC, elyor-doniyorov requested changes
Hi @jssol, 

Good job so far!
## To Highlight 👏 
- [x] There are no linter errors ✔️ 
- [x] Descriptive PR title and description 👍 
- [ ] etc.

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +> Description the project.
- [x] Please provide a descriptive `project title and description` in the Readme file. Because this would make it easy to use your project for future users.

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +- Technologies used
- [x] In this `Built With` section in order to give useful information to users kindly add what technologies you have used to build this project.

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [x] Again, to give useful information for users, please provide a live project link.

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +### Deployment
- [x] In this `Getting Started` section to make your project easy to use, I recommend you to give detailed information about the steps of project installation and setting up process.

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +- etc
- [x] Make sure the README contains an "Acknowledgements" section or similar that gives appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the author of the original design, as required by the [Creative Commons License.](https://creativecommons.org/licenses/)

2022-02-02 10:34 UTC, elyor-doniyorov commented on README.md
> +
- [ ] Kindly record a `video `with a maximum length of 5 minutes presenting the features of the project you built and add it to the Readme file and Pull Request description. It is recommended to use [loom](https://www.loom.com/) to record the video but you can use any tool.

2022-02-02 10:34 UTC, elyor-doniyorov commented on index.html
> +        <span class="ml-text">More</span>
- [ ] I think it would be better if you make the text "More" style `Cocogoose or Lato` currently it is in `Arial` style, please fix it.

2022-02-02 10:34 UTC, elyor-doniyorov commented on styles/about.css
> +  background-color: #2e3139;
- [x] Let's follow the project guidelines and use the recommended colors. For example, for the `partner-section` kindly use \#272A31 instead of that one you have used.

2022-02-02 10:34 UTC, elyor-doniyorov commented on styles/home.css
> +  background-color: #2e3139;
- [x] Same here, please use \#272A31 color instead of \#2e3139 to stick the design as much as possible.

2022-02-02 10:34 UTC, elyor-doniyorov commented on pages/about.html
> +    </nav>
- [ ] I can see you have implemented the hamburger menu for both desktop and mobile sizes. However, if we look at the design the hamburger menu only belongs to mobile size. For desktop size, you should build a different header that contains top and bottom navbars. Let's take a look at the original design below and compare it with your's 👇 
- 
![Screenshot (161)](https://user-images.githubusercontent.com/67087664/152132135-f6c3bf12-d713-4409-b0fd-9b08cb3db51b.png)
Also, please remember this rule is for both pages.

2022-02-02 10:34 UTC, elyor-doniyorov commented on index.html
> +      </p>
- [ ] After this headline, there is the date and address section, please add it too. 👇 
-
![Screenshot (162)](https://user-images.githubusercontent.com/67087664/152132963-6af661c4-ad3c-4059-a835-5ca3e1f14e6a.png)

2022-02-02 10:34 UTC, elyor-doniyorov commented on index.html
> +      <h2 class="program-section-title">Main Program</h2>
- [ ] There are some differences in the horizontal and vertical placement of the `Main Program` sections between your and original design. Take a look to compare and fix it, please. 👇 
- Original design:
- 
![Screenshot (163)](https://user-images.githubusercontent.com/67087664/152133533-68250c18-1a58-42ef-bf69-f589d3046f16.png)
- Your design:
- 
![Screenshot (164)](https://user-images.githubusercontent.com/67087664/152133579-777dd277-558d-4065-89a5-59bcde0791b7.png)
Please remember this rule is for only desktop size you can leave your mobile size as it was before.

2022-02-02 10:34 UTC, elyor-doniyorov commented on scripts/speakers.js
> +  },
- [ ] The same thing here, there are differences in how the `Featured Speakers` sections of yours and original are placed. Yours is placed vertically while the original is horizontal. Let's fix it, too 👇 
- Original :
![Screenshot (166)](https://user-images.githubusercontent.com/67087664/152135033-60fe89de-accc-42d6-a904-c7da80877f32.png)
- Your design below:
![Screenshot (165)](https://user-images.githubusercontent.com/67087664/152135098-9f3f2903-c920-40ce-8d9b-02bd334f1efc.png)
Remember this is for a desktop version.

2022-02-02 10:34 UTC, elyor-doniyorov commented on pages/about.html
> +    <section class="partner-section" id="partner-section">
- [ ] If you take a look at the project desktop design, (but in the mobile size screen the vice versa) you can notice that the Partners section is placed on the `home `page, not on the `about `page. Let's change its placement.

2022-02-02 10:34 UTC, elyor-doniyorov commented on pages/about.html
> +        <li class="editions-list-item">
- [ ] Kindly place the elements in a horizontal row as in the design 👇 
- Original:
- 
![Screenshot (167)](https://user-images.githubusercontent.com/67087664/152137021-667885be-d85d-4657-b001-1c3d303b5b65.png)
- Yours:

![Screenshot (168)](https://user-images.githubusercontent.com/67087664/152136993-6313d62f-0aa0-4582-a10d-f34c1a81e387.png)

2022-02-02 11:47 UTC, jssol commented on styles/about.css
> +  background-color: #2e3139;
The partner section has a background image almost similar to the one I used here.
And this image has the `#272A31` color in it but the `#2e3139` is a lighter version of it for the svg.

2022-02-02 11:51 UTC, jssol commented on styles/home.css
> +  background-color: #2e3139;
The [answer](https://github.com/jssol/africa-tech-report/pull/2#discussion_r797525467) to this is above ⬆️

2022-02-02 11:52 UTC, jssol commented on pages/about.html
> +    </nav>
I haven't worked on the desktop design yet.
I will surely fix this 😄

2022-02-02 11:54 UTC, jssol commented on index.html
> +      </p>
Hello @elyor-doniyorov,
Since the theme of the website is up to us.
The content I chose doesn't need a date and an address, that's why I left that part out.

2022-02-02 11:56 UTC, jssol commented on scripts/speakers.js
> +  },
I am about to fix this

2022-02-03 09:16 UTC, medaminedev66 requested changes
Hi @jssol , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 09:16 UTC, medaminedev66 commented on README.md
> +[What is The Africa Tech Report?](#url)
- [x] The video link is broken. Kindly record a video presenting the features of the project. and add the link of the video to the Readme file.

2022-02-03 09:16 UTC, medaminedev66 commented on README.md
> +
- [x] The "Getting Started" section is a good place to allow visitors(technical and non-technical) to know how to run your project locally. It would be really nice to have that description set up. 😀
Here 👇 is an example of a really good "Getting Started" section

![image](https://user-images.githubusercontent.com/77190203/152309115-0dc90793-fc68-420b-84c9-625ff5794801.png)

2022-02-03 11:16 UTC, jssol commented on README.md
> +
🎉 Thanks for the tip!
I have added the section 😃

2022-02-03 12:26 UTC, medaminedev66 approved these changes
# Hi @jssol , 

### Status: Approved ✔️

:+1: You have implemented all the suggestions. Well Done.

Your project is complete!  There are some optional changes I've suggested to you to make your project best, other than that nothing else to say.
Congratulations! 🎉 


## Optional suggestions
- It would be better if you record another video without background noise. That will impress the visitors and the recruiters.
- In the readme file. I would recommend changing the content of `Getting Started`. Your project is built with HTML, CSS, and JavaScrip, not with Webpacker or React. I would suggest changing the content to the example below:

<img width="507" alt="image" src="https://user-images.githubusercontent.com/77190203/152342331-c57aa221-2bd2-4b01-b684-69cd2f87cd3d.png">


**You may close this Pull Request and merge the changes**

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Amine Smahi_**

------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 12:54 UTC, merged